(()=>{
'use strict';
const ICONS={
'heart':'<path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.6l-1-1a5.5 5.5 0 0 0-7.8 7.8l1 1L12 21l7.8-7.6 1-1a5.5 5.5 0 0 0 0-7.8Z"/>',
'user':'<circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/>',
'calculator':'<rect x="4" y="2.5" width="16" height="19" rx="2"/><path d="M7 6h10v4H7zM8 14h.01M12 14h.01M16 14h.01M8 18h.01M12 18h.01M16 18h.01"/>',
'chevron-down':'<path d="m6 9 6 6 6-6"/>','menu':'<path d="M4 6h16M4 12h16M4 18h16"/>','search':'<circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/>','pin':'<path d="M20 10c0 5-8 11-8 11S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.4"/>','calendar':'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M16 3v4M8 3v4M3 10h18"/>','star':'<path d="m12 2.7 2.9 5.9 6.5.9-4.7 4.6 1.1 6.5L12 17.5l-5.8 3.1 1.1-6.5-4.7-4.6 6.5-.9Z"/>','snow':'<path d="M12 2v20M4.2 6.5l15.6 11M4.2 17.5l15.6-11M8.5 4.5 12 7l3.5-2.5M8.5 19.5 12 17l3.5 2.5"/>','hiking':'<circle cx="14" cy="4" r="2"/><path d="m11 8-2 5 4 2 2-4 3 2M9 13l-3 7M13 15l2 6M6 9l4-1 3 2"/>','bike':'<circle cx="6" cy="17" r="4"/><circle cx="18" cy="17" r="4"/><path d="m6 17 4-8h4l4 8M10 9l5 8M8 9h2M15 6h3"/>','spa':'<path d="M4 18h16M6 15h12M8 12h8M9 4c2 1 2 3 0 5M13 4c2 1 2 3 0 5M17 4c2 1 2 3 0 5"/>','waves':'<path d="M2 9c3 0 3 2 6 2s3-2 6-2 3 2 6 2 3-2 4-2M2 15c3 0 3 2 6 2s3-2 6-2 3 2 6 2 3-2 4-2"/>','surf':'<path d="M6 20c6-2 10-8 12-17M7 4c4 4 5 9 3 14M4 9c5 0 8 3 9 7"/>','family':'<circle cx="8" cy="8" r="3"/><circle cx="17" cy="9" r="2.5"/><path d="M2 21a6 6 0 0 1 12 0M13 21a5 5 0 0 1 9-3"/>','home':'<path d="m3 11 9-8 9 8v10H3Z"/><path d="M9 21v-6h6v6"/>','paraglider':'<path d="M3 8c4-6 14-6 18 0M3 8c2-2 4-2 6 0 2-2 4-2 6 0 2-2 4-2 6 0M12 8v5M12 13l-3 7M12 13l3 7"/>','golf':'<path d="M7 3v16M7 4l9 3-9 3M3 21h8M15 18h.01"/>','grid':'<path d="M4 4h3v3H4zM10.5 4h3v3h-3zM17 4h3v3h-3zM4 10.5h3v3H4zM10.5 10.5h3v3h-3zM17 10.5h3v3h-3zM4 17h3v3H4zM10.5 17h3v3h-3zM17 17h3v3h-3z"/>','sliders':'<path d="M4 7h16M4 17h16M8 4v6M16 14v6"/>','arrow-right':'<path d="M5 12h14M14 7l5 5-5 5"/>','info':'<circle cx="12" cy="12" r="9"/><path d="M12 11v6M12 7h.01"/>','tag':'<path d="M20 13 13 20l-9-9V4h7z"/><circle cx="8.5" cy="8.5" r="1.2"/>','360':'<path d="M4 7a9 9 0 0 1 15 2M20 17a9 9 0 0 1-15-2M18 5h2v4M6 19H4v-4"/><text x="12" y="14" text-anchor="middle" font-size="6" fill="currentColor" stroke="none">360</text>','shield':'<path d="M12 3 20 6v6c0 5-3.2 8-8 10-4.8-2-8-5-8-10V6Z"/><path d="M9 12h6M12 9v6"/>','bell':'<path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/>','headset':'<path d="M4 14v-2a8 8 0 0 1 16 0v2M4 14h3v6H5a2 2 0 0 1-2-2v-2a2 2 0 0 1 1-2ZM20 14h-3v6h2a2 2 0 0 0 2-2v-2a2 2 0 0 0-1-2ZM17 20c-1 2-3 2-5 2"/>','instagram':'<rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r=".7" fill="currentColor" stroke="none"/>','facebook':'<path d="M14 8h4V3h-4c-4 0-6 2-6 6v3H5v5h3v5h5v-5h4l1-5h-5V9c0-1 .4-1 1-1Z"/>','youtube':'<path d="M21 8s0-3-3-3H6C3 5 3 8 3 8v8s0 3 3 3h12c3 0 3-3 3-3Z"/><path d="m10 9 6 3-6 3Z"/>','linkedin':'<path d="M6 9v12M6 5v.01M10 21V9h5a4 4 0 0 1 4 4v8M10 14c1-3 6-3 6 1"/>'
};
function hydrateIcons(root=document){root.querySelectorAll('[data-icon]').forEach(el=>{if(el.dataset.iconReady)return;const key=el.dataset.icon;el.innerHTML=`<svg viewBox="0 0 24 24" aria-hidden="true" focusable="false">${ICONS[key]||ICONS['star']}</svg>`;el.dataset.iconReady='1';});}
hydrateIcons();
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const lang=(document.documentElement.lang||'fr').slice(0,2);
const words={fr:{adults:'adultes',adult:'adulte',children:'enfants',child:'enfant',dates:'Sélectionnez vos dates',activity:'Ski, randonnée, vélo…',searchReady:'Recherche préparée. Le moteur Elloha affichera les résultats selon ces critères sans priorité commerciale.',thanks:'Merci !'},en:{adults:'adults',adult:'adult',children:'children',child:'child',dates:'Select your dates',activity:'Skiing, hiking, cycling…',searchReady:'Search prepared. The Elloha engine will display results using these criteria without commercial ranking priority.',thanks:'Thank you!'},es:{adults:'adultos',adult:'adulto',children:'niños',child:'niño',dates:'Selecciona tus fechas',activity:'Esquí, senderismo, bici…',searchReady:'Búsqueda preparada. El motor Elloha mostrará resultados según estos criterios sin prioridad comercial.',thanks:'¡Gracias!'}}[lang]||{};
// mobile nav
const menu=$('.mobile-menu'), nav=$('#mainNav');menu?.addEventListener('click',()=>{const open=nav.classList.toggle('mobile-open');menu.setAttribute('aria-expanded',String(open))});
// generic dialogs
function openDialog(id){const el=document.getElementById(id);if(!el)return;el.hidden=false;el.setAttribute('aria-hidden','false');document.body.classList.add('modal-open');hydrateIcons(el);setTimeout(()=>el.querySelector('button,[href],input,select')?.focus(),0)}
function closeDialog(el){if(!el)return;el.hidden=true;el.setAttribute('aria-hidden','true');if(!document.querySelector('.dialog-layer:not([hidden])'))document.body.classList.remove('modal-open')}
$$('[data-modal-open]').forEach(b=>b.addEventListener('click',()=>openDialog(b.dataset.modalOpen)));$$('[data-modal-close]').forEach(b=>b.addEventListener('click',()=>closeDialog(b.closest('.dialog-layer'))));document.addEventListener('keydown',e=>{if(e.key==='Escape')$$('.dialog-layer:not([hidden])').forEach(closeDialog)});
// search tabs
$$('[data-search-tab]').forEach(b=>b.addEventListener('click',()=>{$$('[data-search-tab]').forEach(x=>x.classList.remove('is-active'));b.classList.add('is-active');const i=Number(b.dataset.searchTab);if(i===0)$('#destinationInput')?.focus();if(i===1)$('#activityControl')?.click();if(i===2)document.querySelector('.experience-section,.destination-grid')?.scrollIntoView({behavior:'smooth',block:'start'})}));
// mobile search
const shell=$('#searchShell');$('#mobileSearchTrigger')?.addEventListener('click',()=>{shell?.classList.add('is-open');document.body.classList.add('modal-open')});$('#searchClose')?.addEventListener('click',()=>{shell?.classList.remove('is-open');document.body.classList.remove('modal-open')});
// popovers
const popovers=['datePopover','guestPopover','activityPopover'];function togglePop(id){popovers.forEach(p=>{const el=document.getElementById(p);if(el&&p!==id)el.hidden=true});const el=document.getElementById(id);if(el)el.hidden=!el.hidden}
$('#dateControl')?.addEventListener('click',()=>togglePop('datePopover'));$('#guestControl')?.addEventListener('click',()=>togglePop('guestPopover'));$('#activityControl')?.addEventListener('click',()=>togglePop('activityPopover'));
let adults=2,children=0;function guestText(){const a=`${adults} ${adults===1?words.adult:words.adults}`;const c=`${children} ${children===1?words.child:words.children}`;return `${a}, ${c}`}
$$('[data-count]').forEach(b=>b.addEventListener('click',()=>{const type=b.dataset.count,delta=Number(b.dataset.delta);if(type==='adults')adults=Math.min(20,Math.max(1,adults+delta));else children=Math.min(12,Math.max(0,children+delta));$('#adultCount')&&( $('#adultCount').textContent=adults);$('#childCount')&&( $('#childCount').textContent=children);$('#guestSummary')&&( $('#guestSummary').textContent=guestText())}));
function dateSummary(){const a=$('#arrivalDate')?.value,d=$('#departureDate')?.value;if(!a&&!d)return words.dates;const f=s=>s?new Intl.DateTimeFormat(lang==='en'?'en-GB':lang==='es'?'es-ES':'fr-FR',{day:'2-digit',month:'short'}).format(new Date(s+'T12:00:00')):'…';return `${f(a)} – ${f(d)}`}
$('#arrivalDate')?.addEventListener('change',e=>{const dep=$('#departureDate');if(dep){dep.min=e.target.value;if(dep.value&&dep.value<e.target.value)dep.value=''}$('#dateSummary')&&( $('#dateSummary').textContent=dateSummary())});$('#departureDate')?.addEventListener('change',()=>$('#dateSummary')&&( $('#dateSummary').textContent=dateSummary()));
const activityLabels={fr:{ski:'Ski',randonnee:'Randonnée',velo:'Vélo',thermes:'Thermes',plage:'Plage',surf:'Surf',parapente:'Parapente',golf:'Golf',famille:'Famille',nautique:'Activités nautiques'},en:{ski:'Skiing',randonnee:'Hiking',velo:'Cycling',thermes:'Thermal baths',plage:'Beach',surf:'Surfing',parapente:'Paragliding',golf:'Golf',famille:'Family',nautique:'Water activities'},es:{ski:'Esquí',randonnee:'Senderismo',velo:'Bici',thermes:'Termas',plage:'Playa',surf:'Surf',parapente:'Parapente',golf:'Golf',famille:'Familia',nautique:'Actividades acuáticas'}}[lang]||{};let activeActivity='';
function chooseActivity(val){activeActivity=val==='all'?'':val;const label=activityLabels[activeActivity]||words.activity;$('#activitySummary')&&( $('#activitySummary').textContent=label);$$('[data-category],[data-activity]').forEach(x=>x.classList.toggle('is-active',(x.dataset.category||x.dataset.activity)===(val||'all')))}
$$('[data-activity-option]').forEach(b=>b.addEventListener('click',()=>{chooseActivity(b.dataset.activityOption);$('#activityPopover').hidden=true}));$$('[data-activity]').forEach(b=>b.addEventListener('click',()=>chooseActivity(b.dataset.activity)));$$('[data-category]').forEach(b=>b.addEventListener('click',()=>{const val=b.dataset.category;if(val==='all'||activityLabels[val])chooseActivity(val);else openDialog('filtersModal')}));
// filters modal
$('#resetFilters')?.addEventListener('click',()=>$$('#filtersModal input[type=checkbox]').forEach(i=>i.checked=false));$('#applyFilters')?.addEventListener('click',()=>closeDialog($('#filtersModal')));
// search builds neutral results URL (no property promotion on homepage)
function resultsBase(){if(lang==='en')return '/en/accommodations/';if(lang==='es')return '/es/alojamientos/';return '/hebergements/'}
function doSearch(){const q=new URLSearchParams();const dest=$('#destinationInput')?.value.trim();if(dest)q.set('destination',dest);const arr=$('#arrivalDate')?.value,dep=$('#departureDate')?.value;if(arr)q.set('arrival',arr);if(dep)q.set('departure',dep);q.set('adults',String(adults));if(children)q.set('children',String(children));if(activeActivity)q.set('activity',activeActivity);const filters=$$('#filtersModal input:checked').map(i=>i.value);if(filters.length)q.set('filters',filters.join(','));location.href=resultsBase()+(q.toString()?`?${q}`:'')}
$('#searchBtn')?.addEventListener('click',doSearch);$('#destinationInput')?.addEventListener('keydown',e=>{if(e.key==='Enter')doSearch()});
// prefill query on collection pages without displaying promoted properties
const qs=new URLSearchParams(location.search);if(qs.get('destination')&&$('#destinationInput'))$('#destinationInput').value=qs.get('destination');if(qs.get('activity'))chooseActivity(qs.get('activity'));if(qs.get('arrival')&&$('#arrivalDate'))$('#arrivalDate').value=qs.get('arrival');if(qs.get('departure')&&$('#departureDate'))$('#departureDate').value=qs.get('departure');if((qs.get('arrival')||qs.get('departure'))&&$('#dateSummary'))$('#dateSummary').textContent=dateSummary();
// language selector
$('#langSelect')?.addEventListener('change',e=>location.href=e.target.value);
// newsletter UI only
$('#newsletterForm')?.addEventListener('submit',e=>{e.preventDefault();const btn=e.currentTarget.querySelector('button');const old=btn.textContent;btn.textContent=words.thanks;setTimeout(()=>btn.textContent=old,1800)});
// COOKIE CONSENT — compatible with LocPilotAnalytics
const cfg=window.LocPilotTrackingConfig||{};const consentKey='locpilot-cookie-consent';const consentVersion=cfg.consentVersion||'2026-08-platform-v2';const lifetimeDays=Number(cfg.cookieLifetimeDays||183);const banner=$('#cookieBanner'),panel=$('#cookiePanel'),aToggle=$('#cookieAnalytics'),mToggle=$('#cookieMarketing');
const storage={get(){try{return localStorage.getItem(consentKey)}catch(e){return null}},set(v){try{localStorage.setItem(consentKey,v)}catch(e){}}};function readCookie(){const m=document.cookie.match(new RegExp('(?:^|; )'+consentKey.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'=([^;]*)'));return m?decodeURIComponent(m[1]):null}function persist(c){const expiresAt=c.expiresAt||new Date(Date.now()+lifetimeDays*864e5).toISOString();const value=JSON.stringify({necessary:true,analytics:c.analytics===true,marketing:c.marketing===true,version:consentVersion,expiresAt});storage.set(value);document.cookie=`${consentKey}=${encodeURIComponent(value)}; expires=${new Date(expiresAt).toUTCString()}; path=/; SameSite=Lax`;window.LocPilotCookieConsent={necessary:true,analytics:c.analytics===true,marketing:c.marketing===true};window.dispatchEvent(new CustomEvent('locpilot:consent-updated',{detail:window.LocPilotCookieConsent}));return window.LocPilotCookieConsent}function parse(raw){try{const x=JSON.parse(raw);if(!x||x.version!==consentVersion||!x.expiresAt||new Date(x.expiresAt)<new Date())return null;return x}catch(e){return null}}function getConsent(){return parse(storage.get())||parse(readCookie())}function showBanner(){if(!banner)return;banner.hidden=false;banner.setAttribute('aria-hidden','false')}function hideBanner(){if(!banner)return;banner.hidden=true;banner.setAttribute('aria-hidden','true')}function openCookiePanel(){const c=getConsent();if(aToggle)aToggle.checked=c?.analytics===true;if(mToggle)mToggle.checked=c?.marketing===true;openDialog('cookiePanel')}function saveCookieChoice(c){persist(c);hideBanner();closeDialog(panel)}
const existing=getConsent();if(existing){window.LocPilotCookieConsent={necessary:true,analytics:existing.analytics===true,marketing:existing.marketing===true};window.dispatchEvent(new CustomEvent('locpilot:consent-updated',{detail:window.LocPilotCookieConsent}))}else{showBanner()}
$('#cookieBannerAccept')?.addEventListener('click',()=>saveCookieChoice({analytics:true,marketing:true}));$('#cookieBannerReject')?.addEventListener('click',()=>saveCookieChoice({analytics:false,marketing:false}));$('#cookieBannerCustomize')?.addEventListener('click',openCookiePanel);$('#cookieAcceptAll')?.addEventListener('click',()=>saveCookieChoice({analytics:true,marketing:true}));$('#cookieRejectAll')?.addEventListener('click',()=>saveCookieChoice({analytics:false,marketing:false}));$('#cookieSaveChoices')?.addEventListener('click',()=>saveCookieChoice({analytics:aToggle?.checked===true,marketing:mToggle?.checked===true}));$$('[data-cookie-close]').forEach(b=>b.addEventListener('click',()=>closeDialog(panel)));$$('[data-open-cookie-manager]').forEach(b=>b.addEventListener('click',openCookiePanel));
})();
